/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TokenMetadata {
  /**
   * SIP number that defines the JSON schema for metadata. For this SIP, the sip number must be `16`.
   */
  sip: number;
  /**
   * Identifies the asset which this token represents
   */
  name: string;
  /**
   * Describes the asset which this token represents
   */
  description?: string;
  /**
   * A URI pointing to a resource with MIME type image/* representing the asset to which this token represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive. If the token represents a media file of different MIME type or of higher quality defined in property 'raw_media_file_uri', then this image should be used as preview image like a cover for music, or an low-res image.
   */
  image?: string;
  /**
   * Additional attributes of the token that are "observable". See section below. Values may be strings, numbers, object or arrays.
   */
  attributes?: {
    display_type?: string;
    trait_type: string;
    value:
      | {
          [k: string]: unknown;
        }
      | string
      | number
      | number
      | boolean
      | unknown[];
    [k: string]: unknown;
  }[];
  /**
   * Additional other properties of the token. See section below. Values may be strings, numbers, object or arrays.
   */
  properties?: {
    [k: string]: unknown;
  };
  localization?: {
    /**
     * The URI pattern to fetch localized data from. This URI should contain the substring `{locale}` which will be replaced with the appropriate locale value before sending the request. See section about localization for more rules
     */
    uri: string;
    /**
     * The locale of the default data within the base JSON
     */
    default: string;
    /**
     * The list of locales for which data is available. These locales should conform to those defined in the Unicode Common Locale Data Repository (http://cldr.unicode.org/).
     */
    locales: unknown[];
    [k: string]: unknown;
  };
  /**
   * Raw SVG image data. Deprecated. Use `properties.image_data`.
   */
  image_data?: string;
  /**
   * Url to view the item on a 3rd party web site. Deprecated. Use `properties.external_url`.
   */
  external_url?: string;
  /**
   * URL to a multi-media attachment for the item. Deprecated. Use `properties.animation_url`.
   */
  animation_url?: string;
  [k: string]: unknown;
}
